### PR TITLE
Intitial code to allow configuration of options

### PR DESCRIPTION
**Pull request by pchlap**
Hey @dalmouiee,

here is some code I worked on before I went on leave. It allows us to provide configuration to the pydicer tool. It works by storing the config into the hidden .pydicer directory. The PyDicerConfig implementation is Python's way of providing a Singleton class (where one and only one instance can be created and is shared across the entire application). I'd be very curious to hear your feedback. Do you think this is a good way to provide this functionality?

### CODE REVIEW

**Review by dalmouiee — APPROVED** [review]
That's really nice great stuff @pchlap! One note I have is it worth having a JSON to track the actual config options that is then read in by `config.py`, and that way its easier for users to change the JSON file itself rather than `config.py`? Other than that, I think this approach is the way to go for pydicer, happy to merge

**Comment by dalmouiee** [comment]
> That's really nice great stuff @pchlap! One note I have is it worth having a JSON to track the actual config options that is then read in by `config.py`, and that way its easier for users to change the JSON file itself rather than `config.py`? Other than that, I think this approach is the way to go for pydicer, happy to merge

Might be a tad hard actually since the config has python keywords, not sure if a one-to-one conversion of json to python dict would handle this nicely...

**Comment by dalmouiee** [comment]
Whoops, I completely missed that you have a config json tracked! Scratch previous comments, let's merge this through :D

**Comment by pchlap** [comment]
Thanks @dalmouiee, yeah the JSON gets stored in that hidden directory so that would allow the users to modify it there. Or in the CLI later we could provide a function to import (basically just copy) their own JSON config...

But thats great, for now I'll merge this through and build on it as we go :) Thanks!

**Pull request merged**
