### PR TITLE
Code to visualise structures

### PR DESCRIPTION
**Pull request by pchlap**
@dalmouiee here is some code to visualize the structures on an image (might be useful when we run this on the auto-seg data today). Let me know what you think :)

### CODE REVIEW

**Comment by dalmouiee** [comment]
nice great stuff! I'm running the pipeline that runs the visualiser, and I'm getting a weird error when it reaches ```fig = vis.show()``` on line 73:

```
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/60228808/dev/pydicer/pydicer/pipeline.py", line 63, in <module>
    run_test()
  File "/Users/60228808/dev/pydicer/pydicer/pipeline.py", line 59, in run_test
    run(test_input, output_directory=output_directory)
  File "/Users/60228808/dev/pydicer/pydicer/pipeline.py", line 34, in run
    visualise_data.visualise()
  File "/Users/60228808/dev/pydicer/pydicer/visualise/data.py", line 73, in visualise
    fig = vis.show()
  File "/Users/60228808/dev/pydicer/.venv/lib/python3.8/site-packages/platipy/imaging/visualisation/visualiser.py", line 447, in show
    self._add_legend()
  File "/Users/60228808/dev/pydicer/.venv/lib/python3.8/site-packages/platipy/imaging/visualisation/visualiser.py", line 1577, in _add_legend
    approx_font_scaling = self.__figure_size / (
ZeroDivisionError: division by zero
```

the images are saved but the pipeline just crashed after it when it tries to visualise dynamically, which I guess doesn't matter since the images are saved and we can see them manually.

**Comment by pchlap** [comment]
Interesting, thanks @dalmouiee. Which data are you running this across?

**Comment by dalmouiee** [comment]
Ok its not dynamically producing the image, it was just saving! Turns out my input directory had some data that I had been playing around with before so I deleted it and rerun the pipeline to download the zenodo test data. It's working now no hiccups with the pipeline. 

Is it worth eventually adding tests for this module to confirm that images have been saved? Otherwise, it looks good to me happy for a merge :)

**Comment by pchlap** [comment]
Yep defintiely agree that there should be tests. Let me look into what that would involve here.

Based on the error it seems like there might have been a scenario where there was a structure directory but not structures inside? I suppose this is actually possible, in case we convert an RTStruct which only has point or something. I will put a check into the code for that.

**Comment by dalmouiee** [comment]
yeah thats right the structures was empty for me,

**Review by dalmouiee — APPROVED** [review]
LGTM! :)

**Pull request merged**
