### PR TITLE
Add example pipeline jupyter notebook

### PR DESCRIPTION
**Pull request by pchlap**
Hi @Janetxxx & @rnfinnegan,

here's an example jupyter notebook to help run the pydicer pipeline.

@rnfinnegan: At our meeting on Friday we assigned Janet to work on #74, I suggested that you probably already have code floating around which shows how to write text on top of the matplotlib figures generated by the ImageVisualiser. Would you mind sharing a few code snippets with @Janetxxx to help her get started?

### CODE REVIEW

**Comment by rnfinnegan** [comment]
Hello @pchlap and @Janetxxx!
I do already have some code, check out the snippet below:
```
"""
demonstrate adding text to a platipy vis
"""

img = sitk.ReadImage("./ct_hn.nii.gz")

vis = ImageVisualiser(img,figure_size_in=6.5)
fig = vis.show()

# choose axis one
# (this is the top-right box that is blank)
ax = fig.axes[1]

# choose a sensible font size
# this will depend on the figure size you set
fs = 14

# insert some text
ax.text(
    x=0.95,
    y=0.98,
    s="This is green, bold text.",
    color="green",
    ha="right",
    va="top",
    size=fs,
    fontweight="bold"
)

ax.text(
    x=0.95,
    y=0.90,
    s="This is a red text.",
    color="red",
    ha="right",
    va="top",
    size=fs,
    
)

ax.text(
    x=0.95,
    y=0.82,
    s=rf"$\pi={np.pi:.6f}$",
    ha="right",
    va="top",
    size=fs,
    
)
```
Let me know how you go!

**Comment by pchlap** [comment]
Hi @Janetxxx & @rnfinnegan,

are you happy for me to merge this branch to main? Janet you can keep working on it there and make a new branch from main for any changes you contribute :)

If so, could I ask one of you to leave an approval so I can merge? Thanks :)

**Comment by Janetxxx** [comment]
> Hi @Janetxxx & @rnfinnegan,
> 
> here's an example jupyter notebook to help run the pydicer pipeline.
> 
> @rnfinnegan: At our meeting on Friday we assigned Janet to work on #74, I suggested that you probably already have code floating around which shows how to write text on top of the matplotlib figures generated by the ImageVisualiser. Would you mind sharing a few code snippets with @Janetxxx to help her get started?



> Hi @Janetxxx & @rnfinnegan,
> 
> are you happy for me to merge this branch to main? Janet you can keep working on it there and make a new branch from main for any changes you contribute :)
> 
> If so, could I ask one of you to leave an approval so I can merge? Thanks :)

Thanks Phil! Looks good to me.

**Comment by pchlap** [comment]
> Thanks @pchlap Looks good to me!

Thanks @Janetxxx, would you be able to leave a review and mark it as "Approved"? (See the Files Changed Tab and then click "Review Changes") :)

**Review by Janetxxx — APPROVED** [review]
Thanks @pchlap , looks good to me!

**Comment by pchlap** [comment]
> Thanks @pchlap , looks good to me!

Awesome, thanks!

**Pull request merged**
